### ISSUE TITLE
HELP!!!

### ISSUE THREAD

**Issue by kieth1205** [haroldolivieri/MoviesCatalogFlutter#2]
How to add API key in your app?

**Comment by haroldolivieri** [comment]
Hey,

You need to create a file 'api_key.dart' inside data package with a variable API_KEY on it.

**Comment by kieth1205** [comment]
yep, I done it, but issue with your mockdata

**Comment by haroldolivieri** [comment]
Which issue? You can change to the realService if you want too.

**Comment by haroldolivieri** [comment]
on `service.dart` you just can change `MockService()` to `RemoteService()`
